{{- if .Values.softMultiTenancy.enabled -}}
{{- range .Values.managedNamespaces }}
{{- $namespace := . }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $namespace }}
  labels:
    {{- include "eck-operator.labels" $ | nindent 4 }}
    eck.k8s.acceldata.io/tenant: {{ $namespace }}
{{- end -}}
{{- end -}}
