---
apiVersion: kibana.k8s.acceldata.io/v1
kind: Kibana
metadata:
  name: {{ include "kibana.fullname" . }}
  labels:
    {{- include "kibana.labels" . | nindent 4 }}
  annotations:
    eck.k8s.acceldata.io/license: enterprise
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  version: {{ required "A Kibana version is required" .Values.version }}
  {{- toYaml .Values.spec | nindent 2 }}
