bases:
  - ../bases

patchesJson6902:
  # patch that apply to CRDS which might have been installed in v1alpha1 version
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: apmservers.apm.k8s.acceldata.io
    path: add-empty-v1alpha1-patch.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: elasticsearches.elasticsearch.k8s.acceldata.io
    path: add-empty-v1alpha1-patch.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: kibanas.kibana.k8s.acceldata.io
    path: add-empty-v1alpha1-patch.yaml
  # custom patches for APM
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: apmservers.apm.k8s.acceldata.io
    path: remove-pod-template-patch.yaml
  # custom patches for Elasticsearch
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: elasticsearches.elasticsearch.k8s.acceldata.io
    path: elasticsearch-patches.yaml
  # custom patches for Kibana
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: kibanas.kibana.k8s.acceldata.io
    path: remove-pod-template-patch.yaml
  # custom patches for EnterpriseSearch
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: enterprisesearches.enterprisesearch.k8s.acceldata.io
    path: remove-pod-template-patch.yaml
  # custom patches for Beat
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: beats.beat.k8s.acceldata.io
    path: beat-patches.yaml
  # custom patches for Agent
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: agents.agent.k8s.acceldata.io
    path: agent-patches.yaml
  # custom patches for Maps
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: elasticmapsservers.maps.k8s.acceldata.io
    path: maps-patches.yaml
    # custom patches for Logstash
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: logstashes.logstash.k8s.acceldata.io
    path: logstash-patches.yaml


