managedNamespaces: ["team-a", "team-b"]

createClusterScopedResources: true

refs:
  enforceRBAC: true

webhook:
  enabled: true
  namespaceSelector:
    matchExpressions:
      - key: "eck.k8s.acceldata.io/tenant"
        operator: In
        values: ["team-a", "team-b"]


softMultiTenancy:
  enabled: true
