{{- include "elasticagent.daemonset" $ -}}
{{- if $.Values.eck_agent.daemonset.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: eck-agent-daemonset
  namespace: {{ .namespace | default $.Release.Namespace | quote }}
stringData:
  agent.yml: |-
    id: eck-agent-daemonset
    outputs:
      {{ include "elasticagent.elasticOutput" . | indent 6 }}
    secret_references: []
    agent:
      monitoring:
        namespace: {{ .Values.kubernetes.namespace }}
        use_output: default
        enabled: true
        logs: true
        metrics: true
    providers:
      kubernetes_leaderelection:
        enabled: false
      kubernetes:
        node: ${NODE_NAME}
        scope: node
        hints.enabled: false
        kubernetes_secrets:
          enabled: true
    inputs:
    {{- range $configName := $.Values.eck_agent.daemonset.enabled_configs }}
    {{- include (print $configName ".input") $ | nindent 6 }}
    {{- end}}
{{- end}}