apiVersion: v1
kind: Secret
metadata:
  name: eck-agent-deployment
  namespace: {{ .namespace | default $.Release.Namespace | quote }}
stringData:
  agent.yml: |-
    id: eck-agent-deployment
    outputs:
      {{ include "elasticagent.elasticOutput" . | indent 6 }}
    secret_references: []
    agent:
      monitoring:
        namespace: {{ .Values.kubernetes.namespace }}
        use_output: default
        enabled: true
        logs: true
        metrics: true
    providers:
      kubernetes:
        hints:
          {{ .Values.kubernetes.hints | toYaml }}
      kubernetes_leaderelection:
        enabled: false
    inputs:
    {{- include "agent.kubernetes.config.kube_state.input" .Values.kubernetes | nindent 6 }}
    {{- include "agent.kubernetes.config.kube_apiserver.input" .Values.kubernetes | nindent 6 }}