apiVersion: v1
kind: Secret
metadata:
  name: eck-agent-deployment
  namespace: {{ .namespace | default $.Release.Namespace | quote }}
stringData:
  agent.yml: |-
    id: eck-agent-deployment
    outputs:
      default:
        type: elasticsearch
        hosts:
          - {{ .Values.elasticsearch.host | quote }}
        username: {{ .Values.elasticsearch.user | quote  }}
        password: {{ .Values.elasticsearch.pass | quote  }}
    secret_references: []
    agent:
      download:
        sourceURI: 'https://artifacts.elastic.co/downloads/'
      monitoring:
        namespace: {{ .Values.kubernetes.namespace }}
        use_output: default
        enabled: true
        logs: true
        metrics: true
    inputs:
    {{- include "agent.kubernetes.config.kube_state.input" .Values.kubernetes | nindent 6 }}
    {{- include "agent.kubernetes.config.kube_apiserver.input" .Values.kubernetes | nindent 6 }}